### PR TITLE
Several changes, mostly for lyrx->geostyler conversion

### PR DESCRIPTION
**Pull request by volaya**
These changes come from work done at C2C for a customer that needed converting a large set of styles from lyr to SLD. Problems found in that work have been fixed in the commits in this PR, and they make the library more robust and better capable of converting sstyles from the ArcGIS format into geostyler and SLD

There are also some minor changes to other parts of the library.

More details about the changes in this PR can be found here:

https://github.com/camptocamp/bridge-style/wiki

### CODE REVIEW

**Comment by GeoSander** [comment]
Nice work @volaya and @vuilleumierc! And thanks for contributing back!

Since `bridge-style` is a dependency for QGIS Bridge, I'll test this work as soon as possible. Seems that there may be some breaking changes, but all easy to fix.

Q: The PR consists of a lot of tiny commits. Would you mind if I do a Squash & Merge? Alternatively, you could perhaps squash some commits yourself.

**Comment by volaya** [comment]
Yes, feel free to squash them, or at least the ones that affect the module that perfomrs the lyrx to geostyler conversion.

Thanks!

**Comment by GeoSander** [comment]
Well, for a PR, I can only squash everything into one commit or keep all the commits. So if you wish to squash the lyrx->geostyler-related commits, please do so and force push your changes to the `camptocamp:pr_c2c` branch. Then I'll start the review and merge as-is!

**Comment by volaya** [comment]
No need to worry about that, let's squash all the PR

**Review by GeoSander — APPROVED** [review]
Alright, seems good to me! I only need to change some calls to the SLD converter in QGIS Bridge I see.
Thanks again!

**Pull request merged**
