### PR TITLE
add missing QGIS line stroke styles, see #88

### PR DESCRIPTION
**Pull request by geraldo**

### CODE REVIEW

**Comment by GeoSander** [comment]
Thanks, I will have a look @geraldo.
However, I want to release QGIS Bridge 4.4.1 now, so this will not make it in.

**Comment by GeoSander** [comment]
Where did you base those hard-coded dash arrays on @geraldo? 
Just something that looks good? Or do they literally match the dash styles that QGIS has?

I'm a bit hesitant adding this. On the one hand it's a nice addition, on the other hand, I'd rather see a full implementation that supports custom dashes as well. 🤔

**Comment by geraldo** [comment]
@GeoSander Actually they are invented, only based on comparison to make them look similar than the originals...

The custom one actually seems to be a [real value](https://github.com/qgis/QGIS/blob/master/src/core/symbology/qgslinesymbollayer.cpp#L49), but I couldn't figure out how. They seem to come from [somewhere here](https://github.com/qgis/QGIS/blob/master/src/core/symbology/qgsmapinfosymbolconverter.cpp#L36)...

Definitely would be nice to implement the custom dashes, I can't forecast when I would have time to do that so. But it's on my list...

**Comment by GeoSander** [comment]
Ok, thanks for clarifying. In that case, this is as good as it gets for now then. At least we can say that dashes are supported somehow :)

Merging!

**Pull request merged**
