### PR TITLE
Some bug fixes, refactor expressions.py

### LINKED ISSUE #93: String concatenation expression transformed into math additions
**Describe the bug**
When using string concantenation to generate a label from multiple fields in QGIS, it's possible to use the "+" operator.
Exporting it, the generated OGC Filter expression is a `ogc:Add` rather than a `Concatenate` function.

**To Reproduce**

The following screenshot shows the input, the generated map, and the generated SLD:

image

**Expected behavior**
The plugin should recognize the different context and generate a string concatenation expression.

**Environment info (please complete the following information):**
 - OS: Widnows
 - QGIS version: 3.23
 - Bridge version: 4.4.1
 - Python version: whatever is coming with the QGIS installer

### PR DESCRIPTION
**Pull request by GeoSander**
Fixes a couple of reported bugs (see commit details) and bumps the version to `0.1.2`.

[FYI: @vuilleumierc / @ger-benjamin]
This PR refactors moves the `ExpressionConverter` class out of the `togeostyler` QGIS module into the `expressions` module. Pretty much all of the top-level code in `expressions.py` was then moved into the class.
The class is re-instantiated each time `convert()` is called, and I have added a `fields` and `context` property (attribute actually) for feature layers. The context can be used to evaluate an expression (of the first feature) so the resulting output type can be determined. The latter was required to fix #93.

### CODE REVIEW

**Comment by GeoSander** [comment]
To be released as part of `GeoCat Bridge 4.5.0`

**Comment by GeoSander** [comment]
Thank you for the update (and review) @ger-benjamin.
Good to know that you're moving to the real GeoStyler instead. Good decision, I think.

Out of curiosity: will your new approach still be desktop-based, or is it part of a NodeJS-based workflow e.g. with a REST API? Some time ago we also discussed internally if we could set up a GeoStyler-based conversion service with an API and connect to it from QGIS Bridge.

I would actually love to "kill" the bridgestyle project, but on the other hand, I don't want to make the conversion process a challenge for QGIS Bridge users. Installing NodeJS locally therefore is a no-go, but I am also not sure how happy the community would be if we were sending their symbology to a "conversion service" somewhere.

**Comment by ger-benjamin** [comment]
We currently are at an early stage using the geostyler parsers. We can now translate some basic files, but there is a lot of work to have the same quality as in the bridge-style project. And we don't necessarily have a lot of time right now.
The two main/next challenges are : translating style icons and the vendor options we added in the sld part.

The the Geostyler parser are usable in a lot of ways. A CLI is available to translate file, an experimental QGIS plugin is available too, and it's quite easy to setup such js/node parser into a small server. But currently, we use it with a local node commands.

Maybe the QGIS plugin can help you in the future (or we can discuss other solutions later), but that will take a while before to reach the quality of this bridge-style project.

QGIS plugin for info:
https://github.com/geostyler/geostyler-qgis-plugin

**Comment by GeoSander** [comment]
Thanks for your reply @ger-benjamin and mentioning the QGIS GeoStyler plugin. I haven't checked the GeoStyler project(s) in a while now, so I didn't know about it. Seems to be not much more than a wrapper for the CLI though, but it's something.
I also had expected that the lyrx-parser would have been developed much further by now, but that apparently isn't the case.
So don't worry, we won't "kill our darlings" yet :)

**Pull request merged**
